# Generated by Django 3.2.3 on 2021-05-26 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='brief',
            field=models.CharField(default='abc', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='highlighted',
            field=models.TextField(default='abcd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='linenos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='books',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Books', to='auth.user'),
            preserve_default=False,
        ),
    ]
